### PR TITLE
Complete first prototype of the demonstrator

### PR DESCRIPTION
**Pull request by geek-yang**
- Add dropdown menu to the demonstrator, which can be used to select region and season (updating the boxplot data)
- Add maps for each point on the boxplots, which update when that point is clicked
- Add continuous deployment workflow to publish the demonstrator on gh pages

Cordex data clicking doesn't work yet. First need feedback on the naming conventions there. Which preproc data correspond to which maps?

### CODE REVIEW

**Comment by Peter9192** [comment]
I know it's still WIP, but I'll comment already. Really nice so far! This start to look like something.

- I think we need dropdowns only for season and region; the map will take the project and model info it needs from the data in the boxplot. 
- We can make separate boxplot data sources for each combination of season and region, and remove the dropdown from the vega spec. Or, alternatively, we can pimp the vega styling and instead of using an independent dropdown.

**Comment by Peter9192** [comment]
Since you opened the PR, I can't request your review. But still it'd be good if you could have a look at this. Does it (sort of) work on your side? Then I'd like to merge it so we can get feedback.

**Comment by geek-yang** [comment]
Just reviewed all the changes. @Peter9192 well done! Very impressive! And that's quite some work! Thanks a lot for the contribution.

**Comment by Peter9192** [comment]
Thanks for checking! I'll go ahead and merge it then.

**Pull request merged**
